# Generated by Django 3.1.6 on 2021-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Individual', 'Individual'), ('Buisness', 'Buisness')], max_length=255)),
                ('industry', models.CharField(choices=[('Restaurents and Bars', 'Restaurents and Bars'), ('Event Ticketing and Management', 'Event Ticketing and Management'), ('Travel - Airline/Hotel/Cruise/Rentals', 'Travel - Airline/Hotel/Cruise/Rentals'), ('Commericial Real Estate/Building Management', 'Commericial Real Estate/Building Management'), ('Movie Theaters', 'Movie Theaters'), ('Sports/Concerts/Event Venues', 'Sports/Concerts/Event Venues'), ('Schools and Colleges', 'Schools and Colleges'), ('Place of Worship', 'Place of Worship'), ('Reversing Camera', 'Reversing Camera'), ('Government organizations', 'Government organizations')], max_length=100)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
